FinancialCabinet/Controllers/CreditController.cs
using AutoMapper;
using FinancialCabinet.Data;
using FinancialCabinet.Entity;
using FinancialCabinet.Models;
using FinancialCabinet.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace FinancialCabinet.Controllers
{
    public class CreditController : Controller
    {
        private readonly ParserService parserService;
        private readonly BankService bankService;
        private readonly CreditService creditService;
        private readonly IMapper mapper;
        private readonly ApplicationDbContext context;
        private readonly LikeCreditService likeCreditService;
        private readonly RecomendationSystem _recomendation;
        private readonly UserManager<User> _userManager;
        public CreditController(ParserService parserService, BankService bankService, IMapper mapper, ApplicationDbContext context, CreditService creditService, RecomendationSystem recomendation, UserManager<User> userManager, LikeCreditService likeCreditService)
        {
            this.parserService = parserService;
            this.bankService = bankService;
            this.creditService = creditService;
            this.mapper = mapper;
            this.context = context;
            this.likeCreditService = likeCreditService;
            this._recomendation = recomendation;
            this._userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index(int? sortingType, string currencyParam, double? minAmount, double? maxAmount, int? periodFrom, int? periodTo, double? maxPercent, bool? isRecomendation, bool? isLikeCredits)
        {
            List<CreditModel> creditModelList;
            //if (sortingType.HasValue)
            //{
            if (isRecomendation.HasValue && isRecomendation.Value)
            {
                return View(await _recomendation.GetRecomendationCredits(_userManager.GetUserAsync(HttpContext.User).Result.Id));
            }
            creditModelList = await creditService.GetAllAsync(new Dictionary<string, object>() { { "sortingType", sortingType },
                { "currencyParam", currencyParam },
                { "minAmount", minAmount },
                { "maxAmount", maxAmount },
                { "periodFrom", periodFrom },
                { "periodTo", periodTo },
                { "maxPercent", maxPercent },
                { "isForBusiness", User.IsInRole("Business") },
                { "isLikeCredits", isLikeCredits},
                { "userId", _userManager.GetUserAsync(HttpContext.User).Result.Id}
            });
            //}
            //else
            //    creditModelList = await creditService.GetAllAsync();
            return View(creditModelList);
        }

        public async Task<IActionResult> Test(int sortingParam)
        {
            return Content(sortingParam.ToString());
        }

        public async Task<IActionResult> StartParser()
        {
            List<BankModel> bankModelList = mapper.Map<List<Bank>, List<BankModel>>(parserService.ParseBanks());
            await bankService.DeleteAllAsync();
            await bankService.InsertManyAsync(bankModelList);
            return Content("complete");
        }


        [Authorize(Roles = "Individual")]
        public async Task<IActionResult> TestInd()
        {
            return Content("Success individual!");
        }

        [Authorize(Roles = "Business")]
        public async Task<IActionResult> TestBsn()
        {
            return Content("Success individual!");
        }

        public async Task<IActionResult> Like(Guid creditId)
        {
            User user = await _userManager.GetUserAsync(HttpContext.User);
            LikeCreditModel likeCreditModel = likeCreditService.GetAllAsync().Result.Where(e => e.UserID == _userManager.GetUserAsync(HttpContext.User).Result.Id && e.SingleCreditId == creditId).FirstOrDefault();
            if (likeCreditModel == null)
            {
                LikeCreditModel likeCredit = new LikeCreditModel { User = user, SingleCreditId = creditId };
                await likeCreditService.InsertAsync(likeCredit);
                return RedirectToAction("Index");
            }
            else
            {
                await likeCreditService.DeleteByIdAsync(likeCreditModel.ID);
            }
            return RedirectToAction("Index");
        }

    }
}

FinancialCabinet/Controllers/DepositeController.cs
using AutoMapper;
using FinancialCabinet.Data;
using FinancialCabinet.Models;
using FinancialCabinet.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinancialCabinet.Entity;
using Microsoft.AspNetCore.Identity;

namespace FinancialCabinet.Controllers
{
    public class DepositeController: Controller
    {
        private readonly BankService bankService;
        private readonly DepositService depositService;
        private readonly IMapper mapper;
        private readonly ApplicationDbContext context;
        private readonly RecomendationSystem _recomendation;
        private readonly UserManager<User> _userManager;
        private readonly LikeDepositService likeDepositService;

        public DepositeController(BankService bankService, DepositService depositService, IMapper mapper, ApplicationDbContext context, RecomendationSystem recomendation, UserManager<User> userManager, LikeDepositService likeDepositService)
        {
            this.bankService = bankService;
            this.depositService = depositService;
            this.mapper = mapper;
            this.context = context;
            this._recomendation = recomendation;
            this._userManager = userManager;
            this.likeDepositService = likeDepositService;
        }

        public async Task<IActionResult> Index(int? sortingType, string currencyParam, int? periodFrom, int? periodTo, double? maxPercent, bool? isRecomendation, bool? isLikeDeposits)
        {
            List<DepositModel> depositModelsList;
            
            if (isRecomendation.HasValue && isRecomendation.Value)
            {
                return View( await _recomendation.GetRecomendationDeposits(_userManager.GetUserAsync(HttpContext.User).Result.Id));
            }

            depositModelsList = await depositService.GetAllAsync(new Dictionary<string, object>() { { "sortingType", sortingType },
                { "currencyParam", currencyParam },
                { "periodFrom", periodFrom },
                { "periodTo", periodTo },
                { "maxPercent", maxPercent },
                { "isForBusiness", User.IsInRole("Business") },
                { "isLikeDeposits", isLikeDeposits},
                { "userId", _userManager.GetUserAsync(HttpContext.User).Result.Id}
            });

            return View(depositModelsList);
        }

        [HttpGet]
        public async Task<IActionResult> Like(Guid depositId)
        {
            User user = await _userManager.GetUserAsync(HttpContext.User);
            LikeDepositModel likeDepositModel = likeDepositService.GetAllAsync().Result.Where(e => e.UserID == _userManager.GetUserAsync(HttpContext.User).Result.Id && e.SingleDepositID == depositId).FirstOrDefault();
            if (likeDepositModel == null)
            {
                LikeDepositModel likeDeposit = new LikeDepositModel { User = user, SingleDepositID = depositId };
                await likeDepositService.InsertAsync(likeDeposit);
                return RedirectToAction("Index");
            }
            else
            {
                await likeDepositService.DeleteByIdAsync(likeDepositModel.ID);
            }
            return RedirectToAction("Index");
        }
    }
}

FinancialCabinet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Финансовый кабинет</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Финансовый кабинет</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Credit" asp-action="Index">Кредиты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deposite" asp-action="Index">Вклады</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="~/Information.html">Общая информация</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Финансовый кабинет.
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>